import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import cron from 'node-cron';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { sign, requireAuth } from './auth.js';
import { fetchSupplierSnapshot } from './supplier.js';
import { initializeStore, store } from './store.js';

const app = express(), root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
app.use(cors()); app.use(express.json());
const asyncRoute = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);
const productInput=z.object({marketplace:z.string().trim().min(2).max(12).transform(v=>v.toUpperCase()),asin:z.string().trim().length(10).transform(v=>v.toUpperCase()),name:z.string().trim().min(1),imageUrl:z.string().url().optional().or(z.literal('')),status:z.enum(['active','inactive']).default('active'),notes:z.string().optional(),amazonInventory:z.number().int().min(0).default(0)});
const skuInput=z.object({sku:z.string().trim().min(1),variantName:z.string().optional(),inventory:z.number().int().min(0).default(0)});
const supplierInput=z.object({supplierSku:z.string().trim().min(1),purchaseUrl:z.string().url(),specification:z.string().optional(),enabled:z.boolean().default(true)});
app.get('/api/health',(_,res)=>res.json({ok:true}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body),user=store.users.find(u=>u.email===d.email);if(!user||!await bcrypt.compare(d.password,user.password_hash))return res.status(401).json({error:'账号或密码错误'});res.json({token:sign(user),user:{email:user.email,mustChangePassword:user.must_change_password}})}));
app.post('/api/auth/password',requireAuth,asyncRoute(async(req,res)=>{const d=z.object({currentPassword:z.string(),newPassword:z.string().min(8)}).parse(req.body),user=store.users.find(u=>u.id===req.user.id);if(!user||!await bcrypt.compare(d.currentPassword,user.password_hash))return res.status(400).json({error:'当前密码不正确'});user.password_hash=await bcrypt.hash(d.newPassword,12);user.must_change_password=false;await store.save();res.status(204).end()}));
app.use('/api',requireAuth);
app.get('/api/dashboard',(_,res)=>{const products=store.activeProducts(),suppliers=store.users&&store.activeProducts().flatMap(p=>store.productSkus(p.id)).flatMap(s=>store.suppliersForSku(s.id)),week=Date.now()-604800000,runs=[...suppliers.flatMap(s=>store.history(s.id))].filter(r=>Date.parse(r.synced_at)>week);res.json({products:products.length,out_of_stock:products.filter(p=>p.amazon_inventory===0).length,supplier_risk:suppliers.filter(s=>s.enabled&&(s.current_stock==null||s.current_stock===0)).length,failures:runs.filter(r=>r.status==='failed').length,price_rises:0})});
app.get('/api/products',(req,res)=>{const page=Math.max(1,+req.query.page||1),size=Math.min(100,Math.max(1,+req.query.size||20)),q=(req.query.search||'').toLowerCase(),all=store.activeProducts().filter(p=>[p.asin,p.name,p.marketplace].some(v=>v.toLowerCase().includes(q))).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));res.json({items:all.slice((page-1)*size,page*size).map(p=>({...p,sku_count:store.productSkus(p.id).length})),total:all.length,page,size})});
app.post('/api/products',asyncRoute(async(req,res)=>res.status(201).json(await store.createProduct(productInput.parse(req.body)))));
app.get('/api/products/:id',(req,res)=>{const product=store.product(req.params.id);if(!product)return res.status(404).json({error:'产品不存在'});res.json({...product,skus:store.productSkus(product.id).map(s=>({...s,suppliers:store.suppliersForSku(s.id)}))})});
app.put('/api/products/:id',asyncRoute(async(req,res)=>{const p=await store.updateProduct(req.params.id,productInput.parse(req.body));if(!p)return res.status(404).json({error:'产品不存在'});res.json(p)}));
app.delete('/api/products/:id',asyncRoute(async(req,res)=>{if(!await store.deleteProduct(req.params.id))return res.status(404).json({error:'产品不存在'});res.status(204).end()}));
app.post('/api/products/:id/skus',asyncRoute(async(req,res)=>{const s=await store.createSku(req.params.id,skuInput.parse(req.body));if(!s)return res.status(404).json({error:'产品不存在'});res.status(201).json(s)}));
app.put('/api/amazon-skus/:id',asyncRoute(async(req,res)=>{const s=await store.updateSku(req.params.id,skuInput.parse(req.body));if(!s)return res.status(404).json({error:'SKU不存在'});res.json(s)}));
app.delete('/api/amazon-skus/:id',asyncRoute(async(req,res)=>{if(!await store.deleteSku(req.params.id))return res.status(404).json({error:'SKU不存在'});res.status(204).end()}));
app.post('/api/amazon-skus/:id/suppliers',asyncRoute(async(req,res)=>{const s=await store.createSupplier(req.params.id,supplierInput.parse(req.body));if(!s)return res.status(404).json({error:'SKU不存在'});res.status(201).json(s)}));
app.put('/api/suppliers/:id',asyncRoute(async(req,res)=>{const s=await store.updateSupplier(req.params.id,supplierInput.parse(req.body));if(!s)return res.status(404).json({error:'供应商SKU不存在'});res.json(s)}));
app.delete('/api/suppliers/:id',asyncRoute(async(req,res)=>{if(!await store.deleteSupplier(req.params.id))return res.status(404).json({error:'供应商SKU不存在'});res.status(204).end()}));
async function syncOne(id){const supplier=store.supplier(id);if(!supplier)throw Error('供应商SKU不存在');try{const r=await fetchSupplierSnapshot(supplier);await store.recordSync(id,{status:'success',...r});return r}catch(e){await store.recordSync(id,{status:'failed',message:e.message});throw e}}
app.post('/api/suppliers/:id/sync',asyncRoute(async(req,res)=>res.json(await syncOne(req.params.id))));
app.get('/api/suppliers/:id/history',(req,res)=>res.json(store.history(req.params.id)));
app.post('/api/sync/all',asyncRoute(async(_,res)=>{const all=store.activeProducts().flatMap(p=>store.productSkus(p.id)).flatMap(s=>store.suppliersForSku(s.id)).filter(s=>s.enabled);const results=await Promise.allSettled(all.map(s=>syncOne(s.id)));res.json({total:results.length,success:results.filter(r=>r.status==='fulfilled').length,failed:results.filter(r=>r.status==='rejected').length})}));
app.use((err,req,res,next)=>{console.error(err);res.status(err instanceof z.ZodError?400:err.code==='DUPLICATE'?409:500).json({error:err instanceof z.ZodError?'提交的数据无效':err.message||'服务器错误'})});
await initializeStore();
cron.schedule('0 9 * * 1',async()=>{const all=store.activeProducts().flatMap(p=>store.productSkus(p.id)).flatMap(s=>store.suppliersForSku(s.id)).filter(s=>s.enabled);await Promise.allSettled(all.map(s=>syncOne(s.id)));},{timezone:'Asia/Shanghai'});
app.use(express.static(path.join(root,'web','dist')));app.get('*',(_,res)=>res.sendFile(path.join(root,'web','dist','index.html')));
app.listen(process.env.PORT||8080,()=>console.log(`AMZ 管理已启动：http://localhost:${process.env.PORT||8080}`));
